apiVersion: v1
kind: Service
metadata:
  name: webhook-example
  namespace: default
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: webhook-example
  sessionAffinity: None
  type: ClusterIP